# generate_models.py
from typing import Optional, Literal

UNITS_CONFIG = {
    "volume": {
        "metric": {
            "mL": {"class_name": "Milliliters", "plural": "mL"},
            "L": {"class_name": "Liters", "plural": "L"}
        },
        "imperial": {
            "tsp": {"class_name": "Teaspoons", "plural": "tsp"},
            "tbsp": {"class_name": "Tablespoons", "plural": "tbsp"},
            "fl oz": {"class_name": "FluidOunces", "plural": "fl oz"},
            "cup": {"class_name": "Cups", "plural": "cups"},
            "pint": {"class_name": "Pints", "plural": "pints"},
            "quart": {"class_name": "Quarts", "plural": "quarts"},
            "gallon": {"class_name": "Gallons", "plural": "gallons"}
        }
    },
    "weight": {
        "metric": {
            "g": {"class_name": "Grams", "plural": "g"},
            "kg": {"class_name": "Kilograms", "plural": "kg"}
        },
        "imperial": {
            "oz": {"class_name": "Ounces", "plural": "oz"},
            "lb": {"class_name": "Pounds", "plural": "lb"}
        }
    },
    "count": {
        "none": {
            "piece": {"class_name": "Piece", "plural": "pieces"},
            "whole": {"class_name": "Whole", "plural": "whole"},
            "clove": {"class_name": "Clove", "plural": "cloves"},
            "slice": {"class_name": "Slice", "plural": "slices"},
            "bunch": {"class_name": "Bunch", "plural": "bunches"},
            "pinch": {"class_name": "Pinch", "plural": "pinches"},
            "dash": {"class_name": "Dash", "plural": "dashes"},
            "handful": {"class_name": "Handful", "plural": "handfuls"},
            "sprig": {"class_name": "Sprig", "plural": "sprigs"},
            "leaf": {"class_name": "Leaf", "plural": "leaves"},
            "can": {"class_name": "Can", "plural": "cans"},
            "package": {"class_name": "Package", "plural": "packages"},
        }
    }
}


def escape_string_for_literal(s: str) -> str:
    """Escape a string value for use in a Literal type annotation."""
    # Replace single quotes with escaped version for the Literal
    return s.replace("'", "\\'")


def generate_measurement_models():
    """Generate Python code for measurement models."""
    lines = [
        '"""',
        "Auto-generated measurement models.",
        "Do not edit this file directly - regenerate using generate_measurements.py",
        '"""',
        "import typing",
        ""
        "import pydantic",
        "",
        "from utils import float_to_string"
        "",
        "class MeasurementBase(pydantic.BaseModel):",
        '    """Base class for all measurement types with common functionality."""',
        "    unit: str",
        "    plural: str",
        "    amount: float",
        "    type: typing.Optional[str] = None",
        "    system: typing.Optional[str] = None",
        "    ",
        "    def __repr__(self) -> str:",
        '        """Return a string representation of the measurement."""',
        "        if self.amount > 1:",
        "            result = f\"{float_to_string(self.amount)} {self.plural}\"",
        "        else:",
        "            result =  f\"{float_to_string(self.amount)} {self.unit}\"",
        "        if self.system == \"metric\":",
        "            result = result.replace(' ', '')",
        "        return result",
        "   ",
        ""
    ]
    
    models = []
    
    for measurement_type, systems in UNITS_CONFIG.items():
        for system, units in systems.items():
            for unit, config in units.items():
                class_name = config["class_name"]
                plural = config["plural"]
                models.append(class_name)
                
                lines.append(f"class {class_name}(MeasurementBase):")
                # Use double quotes to safely handle underscores and special chars
                lines.append(f'    unit: typing.Literal["{unit}"] = "{unit}"')
                lines.append(f'    plural: typing.Literal["{plural}"] = "{plural}"')
                
                if measurement_type == "count":
                    lines.append(f'    type: None = None')
                    lines.append(f'    system: None = None')
                else:
                    lines.append(f'    type: typing.Literal["{measurement_type}"] = "{measurement_type}"')
                    lines.append(f'    system: typing.Literal["{system}"] = "{system}"')
                
                lines.append("")
    
    lines.append("")
    lines.append(f"Measurement = typing.Union[")
    for i, model in enumerate(models):
        if i == len(models) - 1:
            lines.append(f"    {model}")
        else:
            lines.append(f"    {model},")
    lines.append("]")
    
    return "\n".join(lines)


if __name__ == "__main__":
    code = generate_measurement_models()
    
    # Write to file
    with open("measurements.py", "w") as f:
        f.write(code)
    
    print("Generated measurements.py successfully!")
    
    # Test import
    try:
        import measurements
        print("✅ File imports successfully")
        
        # Test creating instances
        from pydantic import BaseModel, Field
        
        class Ingredient(BaseModel):
            name: str
            measurement: measurements.Measurement = Field(..., discriminator="unit")
        
        test1 = Ingredient(name="milk", measurement={"unit": "fl oz", "amount": 4})
        print(f"✅ FluidOunces test: {test1.measurement.unit}")
        
        test2 = Ingredient(name="flour", measurement={"unit": "g", "amount": 500})
        print(f"✅ Grams test: {test2.measurement.unit}")
        
    except Exception as e:
        print(f"❌ Error: {e}")