"""
Auto-generated measurement models.
Do not edit this file directly - regenerate using generate_measurements.py
"""
import typing
import pydantic

from utils import float_to_string
class MeasurementBase(pydantic.BaseModel):
    """Base class for all measurement types with common functionality."""
    # no unit or plural in some cases e.g. 5 potatos
    unit: typing.Optional[str] = None
    plural: typing.Optional[str] = None
    amount: float
    type: typing.Optional[str] = None
    system: typing.Optional[str] = None
    
    def __repr__(self) -> str:
        """Return a string representation of the measurement."""
        if self.unit is None:
            return f"{float_to_string(self.amount)}"

        if self.amount > 1:
            result = f"{float_to_string(self.amount)} {self.plural}"
        else:
            result =  f"{float_to_string(self.amount)} {self.unit}"

        if self.system == "metric":
            result = result.replace(' ', '')
        return result

class Unitless(MeasurementBase):
    """A bare count with no unit, e.g. '3 eggs' or '8 potatoes'."""
    unit: None = None
    plural: None = None
    type: None = None
    system: None = None

class Milliliters(MeasurementBase):
    unit: typing.Literal["mL"] = "mL"
    plural: typing.Literal["mL"] = "mL"
    type: typing.Literal["volume"] = "volume"
    system: typing.Literal["metric"] = "metric"

class Liters(MeasurementBase):
    unit: typing.Literal["L"] = "L"
    plural: typing.Literal["L"] = "L"
    type: typing.Literal["volume"] = "volume"
    system: typing.Literal["metric"] = "metric"

class Teaspoons(MeasurementBase):
    unit: typing.Literal["tsp"] = "tsp"
    plural: typing.Literal["tsp"] = "tsp"
    type: typing.Literal["volume"] = "volume"
    system: typing.Literal["imperial"] = "imperial"

class Tablespoons(MeasurementBase):
    unit: typing.Literal["tbsp"] = "tbsp"
    plural: typing.Literal["tbsp"] = "tbsp"
    type: typing.Literal["volume"] = "volume"
    system: typing.Literal["imperial"] = "imperial"

class FluidOunces(MeasurementBase):
    unit: typing.Literal["fl oz"] = "fl oz"
    plural: typing.Literal["fl oz"] = "fl oz"
    type: typing.Literal["volume"] = "volume"
    system: typing.Literal["imperial"] = "imperial"

class Cups(MeasurementBase):
    unit: typing.Literal["cup"] = "cup"
    plural: typing.Literal["cups"] = "cups"
    type: typing.Literal["volume"] = "volume"
    system: typing.Literal["imperial"] = "imperial"

class Pints(MeasurementBase):
    unit: typing.Literal["pint"] = "pint"
    plural: typing.Literal["pints"] = "pints"
    type: typing.Literal["volume"] = "volume"
    system: typing.Literal["imperial"] = "imperial"

class Quarts(MeasurementBase):
    unit: typing.Literal["quart"] = "quart"
    plural: typing.Literal["quarts"] = "quarts"
    type: typing.Literal["volume"] = "volume"
    system: typing.Literal["imperial"] = "imperial"

class Gallons(MeasurementBase):
    unit: typing.Literal["gallon"] = "gallon"
    plural: typing.Literal["gallons"] = "gallons"
    type: typing.Literal["volume"] = "volume"
    system: typing.Literal["imperial"] = "imperial"

class Grams(MeasurementBase):
    unit: typing.Literal["g"] = "g"
    plural: typing.Literal["g"] = "g"
    type: typing.Literal["weight"] = "weight"
    system: typing.Literal["metric"] = "metric"

class Kilograms(MeasurementBase):
    unit: typing.Literal["kg"] = "kg"
    plural: typing.Literal["kg"] = "kg"
    type: typing.Literal["weight"] = "weight"
    system: typing.Literal["metric"] = "metric"

class Ounces(MeasurementBase):
    unit: typing.Literal["oz"] = "oz"
    plural: typing.Literal["oz"] = "oz"
    type: typing.Literal["weight"] = "weight"
    system: typing.Literal["imperial"] = "imperial"

class Pounds(MeasurementBase):
    unit: typing.Literal["lb"] = "lb"
    plural: typing.Literal["lb"] = "lb"
    type: typing.Literal["weight"] = "weight"
    system: typing.Literal["imperial"] = "imperial"

class Piece(MeasurementBase):
    unit: typing.Literal["piece"] = "piece"
    plural: typing.Literal["pieces"] = "pieces"
    type: None = None
    system: None = None

class Whole(MeasurementBase):
    unit: typing.Literal["whole"] = "whole"
    plural: typing.Literal["whole"] = "whole"
    type: None = None
    system: None = None

class Clove(MeasurementBase):
    unit: typing.Literal["clove"] = "clove"
    plural: typing.Literal["cloves"] = "cloves"
    type: None = None
    system: None = None

class Slice(MeasurementBase):
    unit: typing.Literal["slice"] = "slice"
    plural: typing.Literal["slices"] = "slices"
    type: None = None
    system: None = None

class Bunch(MeasurementBase):
    unit: typing.Literal["bunch"] = "bunch"
    plural: typing.Literal["bunches"] = "bunches"
    type: None = None
    system: None = None

class Pinch(MeasurementBase):
    unit: typing.Literal["pinch"] = "pinch"
    plural: typing.Literal["pinches"] = "pinches"
    type: None = None
    system: None = None

class Dash(MeasurementBase):
    unit: typing.Literal["dash"] = "dash"
    plural: typing.Literal["dashes"] = "dashes"
    type: None = None
    system: None = None

class Handful(MeasurementBase):
    unit: typing.Literal["handful"] = "handful"
    plural: typing.Literal["handfuls"] = "handfuls"
    type: None = None
    system: None = None

class Sprig(MeasurementBase):
    unit: typing.Literal["sprig"] = "sprig"
    plural: typing.Literal["sprigs"] = "sprigs"
    type: None = None
    system: None = None

class Leaf(MeasurementBase):
    unit: typing.Literal["leaf"] = "leaf"
    plural: typing.Literal["leaves"] = "leaves"
    type: None = None
    system: None = None

class Can(MeasurementBase):
    unit: typing.Literal["can"] = "can"
    plural: typing.Literal["cans"] = "cans"
    type: None = None
    system: None = None

class Package(MeasurementBase):
    unit: typing.Literal["package"] = "package"
    plural: typing.Literal["packages"] = "packages"
    type: None = None
    system: None = None


Measurement = typing.Union[
    Unitless,
    Milliliters,
    Liters,
    Teaspoons,
    Tablespoons,
    FluidOunces,
    Cups,
    Pints,
    Quarts,
    Gallons,
    Grams,
    Kilograms,
    Ounces,
    Pounds,
    Piece,
    Whole,
    Clove,
    Slice,
    Bunch,
    Pinch,
    Dash,
    Handful,
    Sprig,
    Leaf,
    Can,
    Package
]